### ISSUE TITLE
`background-size: cover` is mistreated

### ISSUE THREAD

**Issue by kdex** [jonathantneal/postcss-time-machine#11]
Currently, `background-size: cover` will be transformed to `background-size: cover cover` which is invalid. I think the same will apply to `background-size: contain`.

**Comment by kdex** [comment]
Ping @jonathantneal

**Comment by jonathantneal** [comment]
Thanks for pinging me. I will see if I can fix this tonight.

**Comment by jonathantneal** [comment]
Okay, I went to fix this and saw that this functionality already exists: [index.js#L39](https://github.com/jonathantneal/postcss-time-machine/blob/master/index.js#L39)

And it has a test: [basic test](https://github.com/jonathantneal/postcss-time-machine/blob/master/test/basic.css#L11-L15) and [basic expectation](https://github.com/jonathantneal/postcss-time-machine/blob/master/test/basic.box-sizing.expect.css#L11-L15)

If you can tell me more about what might be going wrong for you, I’ll re-open this.
