### ISSUE TITLE
This plugin breaks the AST, causing cssnano to break

### ISSUE THREAD

**Issue by jhpratt** [jonathantneal/postcss-time-machine#12]
See prior discussion in cssnano/cssnano#658 and ben-eb/postcss-convert-values#27. It appears as though this plugin is the source of the error, though I'm not sure where.

**Comment by jonathantneal** [comment]
Goodness, this plugin needs to be updated. Given time, I will try to work on this tonight. Please continue to ping me if you don’t see regular updates.

**Comment by jonathantneal** [comment]
This is resolved in v4. I wrapped it up last night and gave myself the morning to review and correct a few pieces of documentation.

It also uses PostCSS 7 and supports Node 6.
