### ISSUE TITLE
Fix some before / after statements

### ISSUE THREAD

**Issue by jonathantneal** [jonathantneal/postcss-time-machine#2]
> Boy I just hope nobody actually takes this seriously and uses it in production. Btw some after/before are messed up — [Oskar Krawczyk](https://twitter.com/oskar/status/659392501653086208)

@oskarkrawczyk, the least I can do is fix the before/after statements. Would you mind sharing them?

**Comment by oskarkrawczyk** [comment]
@jonathantneal Now that I look at the docs I realize the before/after references to the PostCSS process not the mistake/what should it be if someone had a time machine.

Everything's ok. Sorry for the confusion.
