### ISSUE TITLE
Box-sizing should be border-box by default.

### ISSUE THREAD

**Issue by rafaelcastrocouto** [jonathantneal/postcss-time-machine#5]
That's an easy one to implement and it does make a lot of sense.

**Comment by TrySound** [comment]
@rafaelcastrocouto It's not about this plugin. And we can't know where need to add this. So, not)

**Comment by jonathantneal** [comment]
@rafaelcastrocouto, I was thinking about how to handle these situations, too. I have some options:

1. Inject 2 rules at the top of the stylesheet
   ```css
   * { box-sizing: inherit; }
   :root { box-sizing: border-box; }
   ````
   And possibly replace any `box-sizing: initial` declarations with `box-sizing: border-box`

2. Recommend a CSS library that does this for you already, like [Sanitize.css](https://github.com/10up/sanitize.css)

What do you think?

**Comment by rafaelcastrocouto** [comment]
Since Sanitize does way more than adding `box-sizing`, I would go for the first one.
But I would only add the 2nd line `:root { box-sizing: border-box; }` and leave all other declarations unchanged. 
That would make easier to control exceptions and avoid unnecessary `!important`.

**Comment by jonathantneal** [comment]
@rafaelcastrocouto, do you mean `* { box-sizing: border-box; }`? Because `:root { box-sizing: border-box; }` won’t do anyone any good.

**Comment by rafaelcastrocouto** [comment]
Yes, u r right ... my bad. `:root` will only apply to the `<html>` tag.

**Comment by jonathantneal** [comment]
I’m going to ask if box-sizing should really have been inherit all along with border-box as an initial root value. If the answer is "no, it should have been box-sizing at an element level all along” then I’ll add this.

**Comment by jonathantneal** [comment]
We have our answer. https://twitter.com/tabatkins/status/674325928843993088

No inheritance, therefore:

```css
* { box-sizing: border-box; }
```

**Comment by rafaelcastrocouto** [comment]
:+1:

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-time-machine/commit/509c79cd8ace39f21612da496079d1d83ec2d96f and published to npm! Thanks, @rafaelcastrocouto.
