### ISSUE TITLE
:link => :link, :visited

### ISSUE THREAD

**Issue by jonathantneal** [jonathantneal/postcss-time-machine#6]
Another “mistake” has been logged by the CSSWG, this one regarding the confusing `:link` pseudo-class.

> `:link` should have had the `:any-link` semantics all along
— https://wiki.csswg.org/ideas/mistakes

The `:any-link` semantics are fairly straight forward.

> The `:any-link` pseudo-class represents an element that acts as the source anchor of a hyperlink. It matches an element if the element would match `:link` or `:visited`.
— https://drafts.csswg.org/selectors/#link

Adding this change will be very similar to [postcss-pseudo-class-any-link](https://github.com/jonathantneal/postcss-pseudo-class-any-link), although modularity of Time Machine should be a separate issue.

I probably would not introduce an `:unvisited` pseudo-class. I asked @TabAtkins about this, but he said `:not(:visited)` could be used if something like that was ever required.

**Comment by MadLittleMods** [comment]
:+1: I am always having to write it out:
```css
.foo {
    &,
    &:visited {
       color: #f00;
    }
}
```

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-time-machine/commit/3bebab5cea4b3f004e3af82a8ec8910a71d09105

https://github.com/jonathantneal/postcss-time-machine#link
