### ISSUE TITLE
border-box without options control issue

### ISSUE THREAD

**Issue by LiaoSept** [jonathantneal/postcss-time-machine#7]
I just need to `background-size` feature

**Comment by jonathantneal** [comment]
I’m not sure I follow. You need an option to disable some feature?

**Comment by septs** [comment]
yep

**Comment by jonathantneal** [comment]
Thanks! All right, now this has been added in [v1.2.1](https://github.com/jonathantneal/postcss-time-machine/tree/v1.2.1).
